/*
=================================================================================
EDA: Magnitude Analysis
=================================================================================
Script Purpose:
    This script focuses the magnitude analysis of measures involves examining 
    the scale and distribution of quantitative values in the measure columns. 
    This analysis helps identify outliers, trends, and patterns that may impact 
    data interpretation and decision-making.

Usage:
    - Use these analyses to identify outliers, trends, and patterns.
=================================================================================
*/ 
-- 1. Find the total customers by countries
SELECT 
	country,
	COUNT(DISTINCT customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- 2. Find the total customers by gender
SELECT 
	gender,
	COUNT(DISTINCT customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- 3. Find total products by category
SELECT 
	category,
	COUNT(DISTINCT product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- 4. What is the average costs in each category
SELECT 
	category,
	AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- 5. What is the total revenue generated for each category
SELECT
	dp.category,
	FORMAT(SUM(fs.sales_amount), 'C0') AS total_revenue	
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_products AS dp
ON fs.product_key = dp.product_key
GROUP BY dp.category
ORDER BY SUM(fs.sales_amount) DESC;

-- 6. Find the total revenue generated by each customer
SELECT
	dc.customer_id,
	dc.first_name,
	dc.last_name,
	FORMAT(SUM(fs.sales_amount), 'C0') AS total_revenue	
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_customers AS dc
ON fs.customer_key = dc.customer_key
GROUP BY 
	dc.customer_id,
	dc.first_name,
	dc.last_name
ORDER BY SUM(fs.sales_amount) DESC;

-- 7. What is the distribution of sold items across countries
SELECT
	dc.country,
	FORMAT(SUM(fs.quantity), 'N0') AS sold_items
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_customers AS dc
ON fs.customer_key = dc.customer_key
GROUP BY dc.country
ORDER BY SUM(fs.quantity) DESC;
